Convert front to react
jrodrigoav/coe-learning-path pull request #2
Opened 2023-05-19 23:13 UTC by Brianx03

Created React version of Coe Learning Path front end

2023-05-20 18:12 UTC, jrodrigoav requested changes
NO veo el codigo de react, deberai ser WEB/coelearningpath-react

2023-05-21 04:51 UTC, Brianx03 commented
> NO veo el codigo de react, deberai ser WEB/coelearningpath-react
No me dí cuenta que marcó error en el push, está mal el PR. Sabes como arreglar lo del push?

![image](https://github.com/jrodrigoav/coe-learning-path/assets/35542150/a09ff5c7-11a4-4c1a-b9bf-1c5fafbec949)

@jrodrigoav

2023-05-21 06:19 UTC, jrodrigoav commented
ahrega al gitignore el.directorio de .parcel-cache y borralo del repo

2023-05-24 23:30 UTC, jrodrigoav requested changes
Hay que hace cleanup de los archivos que estan en los directorios fuera de las carpetas de cada aplicacion

2023-07-25 01:21 UTC, merged